In [5]:
import ants
import os, shutil
import subprocess
import nibabel as nib
import pandas as pd 

from glob import glob
from natsort import natsorted, natsort_keygen

In [6]:
sourcepath = '/Users/arnaud/Downloads/sourcedata_orig'

In [8]:
subjects = glob(sourcepath+'/sub*/')
scans = glob(sourcepath+'/sub*/ses*/anat/*.nii.gz')

print(f"# subjects : {len(subjects)}, # scans {len(scans)}")

# subjects : 505, # scans 1050

In [9]:
csvpath = '/Users/arnaud/Desktop/sourcedata_orig/participants.tsv'
ds_info = pd.read_csv(csvpath, sep ='\t')
ds_info.head()

  participant_id  gender  birth_age  birth_weight singleton
0    CC00549XX22  Female  42.000000         3.685    Single
1    CC00576XX16    Male  28.857143         0.850    Single
2    CC00202XX04    Male  38.571429         2.630    Single
3    CC00720XX11  Female  40.428571         3.950    Single
4    CC00388XX18  Female  34.428571         2.800    Single

In [10]:
input_data = natsorted(glob(f"{sourcepath}/sub*/ses*/anat/*"))
print(f"Total dhcp :{len(input_data)}")
outputdir = "../dhcp_register/"
os.makedirs(outputdir, exist_ok=True)

# csv aligning
csvpath = '/Users/arnaud/Desktop/sourcedata_orig/participants.tsv'
ds_info = pd.read_csv(csvpath, sep ='\t')
sorted_ds = ds_info.sort_values(by="participant_id", key=natsort_keygen())

Total dhcp :1050

In [21]:
sorted_ds

    participant_id  gender  birth_age  birth_weight singleton
174    CC00058XX09    Male  40.285714         4.135    Single
132    CC00060XX03  Female  40.142857         2.845    Single
479    CC00062XX05  Female  41.285714         4.050    Single
33     CC00063AN06  Female  35.142857         1.950  Multiple
477    CC00065XX08    Male  40.428571         3.400    Single
..             ...     ...        ...           ...       ...
212    CC00863XX14  Female  41.571429         3.910    Single
317    CC00871XX14    Male  40.285714         4.110    Single
285    CC00879XX22  Female  40.142857         3.650    Single
150    CC00889BN24  Female  33.142857         2.460  Multiple
25     CC00907XX16    Male  34.428571         2.100    Single

[505 rows x 5 columns]

In [40]:
input_data[:5]

['/Users/arnaud/Downloads/sourcedata_orig/sub-CC00058XX09/ses-11300/anat/sub-CC00058XX09_ses-11300_T2w.nii.gz',
 '/Users/arnaud/Downloads/sourcedata_orig/sub-CC00060XX03/ses-12501/anat/sub-CC00060XX03_ses-12501_T1w.nii.gz',
 '/Users/arnaud/Downloads/sourcedata_orig/sub-CC00060XX03/ses-12501/anat/sub-CC00060XX03_ses-12501_T2w.nii.gz',
 '/Users/arnaud/Downloads/sourcedata_orig/sub-CC00062XX05/ses-13801/anat/sub-CC00062XX05_ses-13801_T1w.nii.gz',
 '/Users/arnaud/Downloads/sourcedata_orig/sub-CC00062XX05/ses-13801/anat/sub-CC00062XX05_ses-13801_T2w.nii.gz']

In [28]:
sorted_ds['participant_id'].iloc[0]

'CC00058XX09'

In [39]:
for i, scan_path in enumerate(input_data[:5]):
    # print(p:=scan_path.split("/")[5][4:])
    # if scan_path.split("/")[5][4:] == sorted_ds['participant_id'].iloc[i]:
    #     print(i)
    print(sorted_ds[sorted_ds['participant_id'] == scan_path.split("/")[5][4:]]['birth_age'].astype('int').values)

[40]
[40]
[40]
[41]
[41]

In [ ]:
path_templates = '/Users/arnaud/Documents/GitHub/dhcp-volumetric-atlas-groupwise/mean/'