# Notebook : creating the available MRIs datatable

In [1]:
import pandas as pd 
import ants
from glob import glob
from natsort import natsorted
from tqdm.notebook import tqdm

In [2]:
df = pd.DataFrame(columns=["dataset", "mode", "id", "ses", "gender", "source_file", "mni_file", "aseg1", "qc", "vol"])

In [3]:
# removed skulls results from skull_strip in this folder, it is now quite clean
# !ls /Users/arnaud/Downloads/sourcedata_orig/sub*/ses*/anat/*skull*.* | wc -l
# !rm /Users/arnaud/Downloads/sourcedata_orig/sub*/ses*/anat/*skull*.*
# !rm -rf /Users/arnaud/Downloads/sourcedata_orig/sub*/ses*/[dwi-func-fmap]

In [90]:
!ls /Users/arnaud/Downloads/sourcedata_orig/sub*/ses*/anat/* | wc -l

    1050

In [5]:
dhcp_datadir = "/Users/arnaud/Downloads/sourcedata_orig"
dhcp_uniques = natsorted(glob(f"{dhcp_datadir}/sub*/ses*/anat/*.*"))
# 1050 : 492 (T1) + 558 (T2)
len(dhcp_uniques)

1050

In [27]:
participants = pd.read_csv("/Users/arnaud/Downloads/sourcedata_orig/participants.tsv", sep="\t")
participants.head(3)

  participant_id  gender  birth_age  birth_weight singleton
0    CC00549XX22  Female  42.000000         3.685    Single
1    CC00576XX16    Male  28.857143         0.850    Single
2    CC00202XX04    Male  38.571429         2.630    Single

In [75]:
DATASET = "dhcp"
rows = []
for i, scan in tqdm(enumerate(dhcp_uniques[:10]), total=len(dhcp_uniques)):
    parts = scan.split("/")
    subject_id = parts[-4] # sub-XXXX
    session_id = parts[-3] # ses-XX
    img = parts[-1]

    gender = participants[participants["participant_id"] == f"{subject_id[4:]}"]['gender'].item(),
    age = participants[participants["participant_id"] == f"{subject_id[4:]}"]['birth_age'].item()

    dict1 = {"dataset": DATASET, 
             "mode": "T1" if "T1" in img else "T2", 
             "id": subject_id[4:], # remove sub- prefix
             "ses": session_id[4:],# remove ses- prefix
             "gender": gender[0],
             "gest_age": f"{age:.1f}",
             "source_file": scan,
             "mni_file": None,
             "aseg1": None,
             "qc": None,
             "vol": None
    }

    rows.append(dict1)

df = pd.DataFrame(rows)
df

  0%|          | 0/1050 [00:00<?, ?it/s]

,dataset,mode,id,ses,gender,gest_age,source_file,mni_file,aseg1,qc,vol
0,dhcp,T2,CC00058XX09,11300,Male,40.3,/Users/arnaud/Downloads/sourcedata_orig/sub-CC...,None,None,None,None
1,dhcp,T1,CC00060XX03,12501,Female,40.1,/Users/arnaud/Downloads/sourcedata_orig/sub-CC...,None,None,None,None
2,dhcp,T2,CC00060XX03,12501,Female,40.1,/Users/arnaud/Downloads/sourcedata_orig/sub-CC...,None,None,None,None
3,dhcp,T1,CC00062XX05,13801,Female,41.3,/Users/arnaud/Downloads/sourcedata_orig/sub-CC...,None,None,None,None
4,dhcp,T2,CC00062XX05,13801,Female,41.3,/Users/arnaud/Downloads/sourcedata_orig/sub-CC...,None,None,None,None
5,dhcp,T1,CC00063AN06,15102,Female,35.1,/Users/arnaud/Downloads/sourcedata_orig/sub-CC...,None,None,None,None
6,dhcp,T2,CC00063AN06,15102,Female,35.1,/Users/arnaud/Downloads/sourcedata_orig/sub-CC...,None,None,None,None
7,dhcp,T1,CC00065XX08,18600,Male,40.4,/Users/arnaud/Downloads/sourcedata_orig/sub-CC...,None,None,None,None
8,dhcp,T2,CC00065XX08,18600,Male,40.4,/Users/arnaud/Downloads/sourcedata_orig/sub-CC...,None,None,None,None
9,dhcp,T1,CC00066XX09,19200,Male,38.3,/Users/arnaud/Downloads/sourcedata_orig/sub-CC...,None,None,None,None

In [85]:
registered = natsorted(glob("/Users/arnaud/Documents/GitHub/RESEARCH-MRI-Analysis/code/volumes/mri_register/dhcp/*"))

parts = registered[0].split("/")
session_id_reg =  parts[-1].split("_")[1]
session_id_reg[4:]

for i, r in df.iterrows():
    if r['mode']=='T1' and r['ses'] == session_id_reg[4:]:
        print(r)
    df.iloc[i]['mni_file'] =

dataset                                                     dhcp
mode                                                          T1
id                                                   CC00060XX03
ses                                                        12501
gender                                                    Female
gest_age                                                    40.1
source_file    /Users/arnaud/Downloads/sourcedata_orig/sub-CC...
mni_file                                                    None
aseg1                                                       None
qc                                                          None
vol                                                         None
Name: 1, dtype: object

'dhcp'